services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7331:7331"
    volumes:
      - database:/app/storage
      - ./static:/app/static
      - ./.env:/app/.env 
    restart: unless-stopped
    
volumes:
  database: