services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7331:7331"
    volumes:
      - ./storage.db:/app/storage.db
      - ./static:/app/static
      - ./.env:/app/.env 
    restart: unless-stopped