services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AIRSTATION_PLAYER_TITLE=${AIRSTATION_PLAYER_TITLE}
    ports:
      - "7331:7331"
    volumes:
      - database:/app/storage
      - ./static:/app/static
    restart: unless-stopped
    env_file:
      - .env
    
volumes:
  database: